# V-280094 SV-280094r1184607 RHEL-10-700970 SRG-OS-000324-GPOS-00125
- name: stigrule_280094__disable_debug-shell
  ansible.builtin.systemd_service:
    name: debug-shell
    enabled: false
    masked: true
    state: stopped
  when: rhel10STIG_stigrule_280094_manage

# V-280931 SV-280931r1197213 RHEL-10-001020 SRG-OS-000366-GPOS-00153
- name: Ensure sequoia-sq package installed
  ansible.builtin.package:
    name: sequoia-sq
    state: present
  when: rhel10STIG_stigrule_280931_manage

- name: Ensure RPM-GPG-KEY-redhat-release file exists
  ansible.builtin.file:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
    state: touch
    owner: root
    group: root
    mode: "0644"
  when: rhel10STIG_stigrule_280931_manage

- name: Get fingerprints in current RPM-GPG-KEY-redhat-release file
  ansible.builtin.command:
    cmd: sq inspect /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  register: sq_file
  changed_when: false
  when: rhel10STIG_stigrule_280931_manage

- name: Query rpm for gpg-pubkey
  ansible.builtin.shell: |
    set -o pipefail
    rpm -qa gpg-pubkey --qf '%{Description}\n' | sq inspect
  changed_when: false
  register: sq_rpm
  when: rhel10STIG_stigrule_280931_manage

- name: Extract current RPM file fingerprints
  ansible.builtin.set_fact:
    current_file_fingerprints: >-
      {{
        sq_file.stdout_lines
        | select('search', '^Fingerprint:')
        | map('regex_replace', '^Fingerprint:\\s*', '')
        | map('regex_replace', '\\s+', '')
        | list
      }}
  when: rhel10STIG_stigrule_280931_manage

- name: Extract current RPM db fingerprints
  ansible.builtin.set_fact:
    current_rpm_fingerprints: >-
      {{
        sq_rpm.stdout_lines
        | select('search', '^Fingerprint:')
        | map('regex_replace', '^Fingerprint:\\s*', '')
        | map('regex_replace', '\\s+', '')
        | list
      }}
  when: rhel10STIG_stigrule_280931_manage

- name: Process each source key file
  ansible.builtin.include_tasks: process_rpm_keys.yml
  loop: "{{ rhel10STIG_stigrule_280931_source_keys }}"
  loop_control:
    loop_var: source_key_path
  when: rhel10STIG_stigrule_280931_manage

# V-280932 SV-280932r1197215 RHEL-10-001030 SRG-OS-000366-GPOS-00153
- name: Stat yum/dnf config files
  ansible.builtin.stat:
    path: "{{ item }}"
    get_checksum: false
    get_mime: false
    follow: true
  loop:
    - /etc/yum.conf
    - /etc/dnf/dnf.conf
  register: main_conf_stats

- name: Find repo files
  ansible.builtin.find:
    paths: /etc/yum.repos.d
    patterns: "*.repo"
    file_type: file
  register: repo_files

- name: Get sections from repo files
  ansible.builtin.command: >
    awk -F'[][]' '/^\s*\[.*\]\s*$/ {print $2}' {{ item.path }}
  register: repo_sections_cmd
  loop: "{{ repo_files.files }}"
  changed_when: false
  when:
    - repo_files.files | length > 0

- name: Build list of {path, section} dicts
  ansible.builtin.set_fact:
    repo_path_section_dicts: "{{ repo_path_section_dicts | default([]) + new_pairs }}"
  vars:
    new_pairs: >-
      {{
        item.stdout_lines
        | map('community.general.dict_kv', 'section')
        | map('combine', {'path': item.item.path})
        | list
      }}
  loop: "{{ repo_sections_cmd.results }}"
  loop_control:
    label: "{{ item.item.path }}"
  when:
    - repo_sections_cmd.results | length > 0

- name: stigrule_280932__gpgcheck_main_conf_files
  community.general.ini_file:
    path: "{{ item.item }}"
    section: main
    option: gpgcheck
    value: 1
    ignore_spaces: true
    exclusive: true
    follow: true
    mode: '0644'
    owner: root
    group: root
  loop: "{{ main_conf_stats.results }}"
  when:
    - rhel8STIG_stigrule_280932_Manage
    - item.stat.exists

# V-280933 SV-280933r1197217 RHEL-10-001040 SRG-OS-000366-GPOS-00153
- name: stigrule_280933__local_gpgcheck_main_conf_files
  community.general.ini_file:
    path: "{{ item.item }}"
    section: main
    option: localpkg_gpgcheck
    value: 1
    ignore_spaces: true
    exclusive: true
    follow: true
    mode: '0644'
    owner: root
    group: root
  loop: "{{ main_conf_stats.results }}"
  when:
    - rhel8STIG_stigrule_280933_Manage
    - item.stat.exists

# V-280934 SV-280934r1165157 RHEL-10-001050 SRG-OS-000366-GPOS-00153
- name: stigrule_280934__gpgcheck_main_conf_files
  community.general.ini_file:
    path: "{{ item.path }}"
    section: "{{ item.section }}"
    option: gpgcheck
    value: 1
    ignore_spaces: true
    exclusive: true
    follow: true
    mode: '0644'
    owner: root
    group: root
  loop: "{{ repo_path_section_dicts }}"
  when:
    - rhel8STIG_stigrule_280934_Manage
    - repo_path_section_dicts is defined

# V-280942 SV-280942r1165181 RHEL-10-200000 SRG-OS-000437-GPOS-00194
- name: stigrule_280942__set_clean_requirements_on_remove
  community.general.ini_file:
    path: "{{ item.item }}"
    section: main
    option: clean_requirements_on_remove
    value: "True"
    ignore_spaces: true
    exclusive: true
    follow: true
    mode: '0644'
    owner: root
    group: root
  loop: "{{ main_conf_stats.results }}"
  when:
    - rhel8STIG_stigrule_280942_Manage
    - item.stat.exists

# V-280943 SV-280943r1165184 RHEL-10-200010 SRG-OS-000095-GPOS-00049
- name: stigrule_280943__verify_nfs-utils_absent
  ansible.builtin.package:
    name: nfs-utils
    state: absent
  when: rhel10STIG_stigrule_280943_manage

# V-280944 SV-280944r1184749 RHEL-10-200020 SRG-OS-000095-GPOS-00049
- name: stigrule_280944__verify_telnet-server_absent
  ansible.builtin.package:
    name: telnet-server
    state: absent
  when: rhel10STIG_stigrule_280944_manage

# V-280945 SV-280945r1184750 RHEL-10-200030 SRG-OS-000095-GPOS-00049
- name: stigrule_280945__verify_gssproxy_absent
  ansible.builtin.package:
    name: gssproxy
    state: absent
  when: rhel10STIG_stigrule_280945_manage

# V-280946 SV-280946r1184751 RHEL-10-200040 SRG-OS-000095-GPOS-00049
- name: stigrule_280946__verify_tuned_absent
  ansible.builtin.package:
    name: tuned
    state: absent
  when: rhel10STIG_stigrule_280946_manage

# V-280947 SV-280947r1165196 RHEL-10-200050 SRG-OS-000095-GPOS-00049
- name: stigrule_280947__verify_tftp-server_absent
  ansible.builtin.package:
    name: tftp-server
    state: absent
  when: rhel10STIG_stigrule_280947_manage

# V-280948 SV-280948r1197218 RHEL-10-200060 SRG-OS-000095-GPOS-00049
- name: stigrule_280948__verify_unbound_absent
  ansible.builtin.package:
    name: unbound
    state: absent
  when: rhel10STIG_stigrule_280948_manage

# V-280949 SV-280949r1195338 RHEL-10-200070 SRG-OS-000074-GPOS-00042
- name: stigrule_280949__verify_tftp_absent
  ansible.builtin.package:
    name: tftp
    state: absent
  when: rhel10STIG_stigrule_280949_manage

# V-280950 SV-280950r1165205 RHEL-10-200080 SRG-OS-000095-GPOS-00049
- name: stigrule_280950__verify_gdm_absent
  ansible.builtin.package:
    name: gdm
    state: absent
  when: rhel10STIG_stigrule_280950_manage
